work

diff --git a/.github/workflows/detect-flaky-test.yml b/.github/workflows/detect-flaky-test.yml
--- a/.github/workflows/detect-flaky-test.yml
+++ b/.github/workflows/detect-flaky-test.yml
@@ -33,18 +33,54 @@ jobs:
       matrix:
         java: [ 8, 17, 21 ]
     steps:
-      # step 2
-      - name: "Download test reports artifact for run 2"
-        uses: actions/download-artifact@v4
-        with:
-          name: run-2-surefire-reports-${{ matrix.java }}
-          path: reports-2-${{ matrix.java }}
       # step 1
-      - name: "Download test reports artifact for run 1"
-        uses: actions/download-artifact@v4
-        with:
-          name: run-1-surefire-reports-${{ matrix.java }}
-          path: reports-1-${{ matrix.java }}
+      - name: Download artifact run-1-surefire-reports-${{ matrix.java }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          RUN_ID: ${{ github.event.workflow_run.id }}
+          ARTIFACT_NAME: run-1-surefire-reports-${{ matrix.java }}
+          OUTPUT_DIR: reports-1-${{ matrix.java }}
+        run: |
+          echo "Fetching artifacts for workflow run ID: $RUN_ID"
+          artifacts_url="https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID/artifacts"
+
+          # get download url
+          artifact_url=$(curl -s -H "Authorization: token $GITHUB_TOKEN" $artifacts_url \
+            | jq -r --arg name "$ARTIFACT_NAME" '.artifacts[] | select(.name == $name) | .archive_download_url')
+
+          if [ -z "$artifact_url" ]; then
+            echo "❌ Artifact not found: $ARTIFACT_NAME"
+            exit 1
+          fi
+
+          echo "✅ Found artifact: $ARTIFACT_NAME"
+          curl -L -H "Authorization: token $GITHUB_TOKEN" "$artifact_url" -o artifact.zip
+          mkdir -p "$OUTPUT_DIR"
+          unzip artifact.zip -d "$OUTPUT_DIR"
+      # step 2
+      - name: Download artifact run-2-surefire-reports-${{ matrix.java }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          RUN_ID: ${{ github.event.workflow_run.id }}
+          ARTIFACT_NAME: run-2-surefire-reports-${{ matrix.java }}
+          OUTPUT_DIR: reports-1-${{ matrix.java }}
+        run: |
+          echo "Fetching artifacts for workflow run ID: $RUN_ID"
+          artifacts_url="https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID/artifacts"
+
+          # get download url
+          artifact_url=$(curl -s -H "Authorization: token $GITHUB_TOKEN" $artifacts_url \
+            | jq -r --arg name "$ARTIFACT_NAME" '.artifacts[] | select(.name == $name) | .archive_download_url')
+
+          if [ -z "$artifact_url" ]; then
+            echo "❌ Artifact not found: $ARTIFACT_NAME"
+            exit 1
+          fi
+
+          echo "✅ Found artifact: $ARTIFACT_NAME"
+          curl -L -H "Authorization: token $GITHUB_TOKEN" "$artifact_url" -o artifact.zip
+          mkdir -p "$OUTPUT_DIR"
+          unzip artifact.zip -d "$OUTPUT_DIR"
       # step 3
       - name: "Use Python 3.x"
         uses: actions/setup-python@v2
